name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
       id-token: write
       contents: read    
    steps:
      - uses: actions/checkout@v4
        with:
          repository: matthuisman/i.mjh.nz.git
          path: .
          ref: master

      
      - name: Build site
        run: echo "" > index.html
      - name: Deploy
        uses: actions/deploy-pages@v1
